# Generated by Refit version: 0.1.0

from refit.host import Host
from refit.registry import HostRegistry


host_registry = HostRegistry()


@host_registry.register(environment="production")
class PetShopProduction(Host):
    address = "127.0.0.1"
    environment_vars = {}


@host_registry.register(environment="test")
class PetShopTest(Host):
    address = "127.0.0.1"
    environment_vars = {}
