# Generated by Refit version: 0.1.0

from refit.task import Task
from refit.registry import TaskRegistry


task_registry = TaskRegistry()


@task_registry.register
class PetShop(Task):
    """
    Provision PetShop.
    """

    async def run(self):
        path = "/tmp/hello_world"

        if not await self.path_exists(path):
            await self.create_folder(path)

        await self.raw('touch /tmp/hello_world/greetings.txt')
